apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-persist
  namespace: jenkins-project
spec:
  storageClassName: jenkins-persist
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /storage/jenkins-volume/